back_office_homepage:
    path:     /
    defaults: { _controller: BackOfficeBundle:Dashboard:index }

Back_office_ajouterproduit:
    path:     /ajouterproduit
    defaults: { _controller:BackOfficeBundle:ProduitBack:ajouterproduit }

Back_office_ajout:
    path:     /ajout
    defaults: { _controller:BackOfficeBundle:ProduitBack:ajout }